#!/bin/sh

get_session() {
  local SESSION=$(shuf -n 1 /usr/share/dict/words | tr -cd "[:alpha:]")
  echo $SESSION
}

open_tmux() {
  local SESSION=$(get_session)
  echo $SESSION

  tmux new -s $SESSION
}

open_tmux $@
